### ISSUE TITLE
[Errno 2] No such file or directory: 'clip.exe'

### ISSUE THREAD

**Issue by CA-TT-AC** [niuzaisheng/ScreenAgent#29]
Hi, thanks for your code releasing of such great work.

I am using your docker for building a VNC environment, but I found keyboard control does not work. I tried to use the given command to locate problem, 
```
curl --location 'http://localhost:8001/clipboard' \
--header 'Content-Type: application/json' \
--data '{
    "text":"Hello world",
    "token":"<CLIPBOARD_SERVER_SECRET_TOKEN>"
}'
```
It outputs
```
{"detail":"[Errno 2] No such file or directory: 'clip.exe'"}
```
Should I install something in that docker? It will be helpful if you can reply!

**Comment by CA-TT-AC** [comment]
This problem has been solved, referring to https://github.com/asweigart/pyperclip/issues/194.

**Comment by Jeffry-wen** [comment]
> This problem has been solved, referring to [asweigart/pyperclip#194](https://github.com/asweigart/pyperclip/issues/194).

Hi, I have also encountered the same situation, I commented the check statement according to your guidance, but there is still a problem, specifically, there is this error in the check clipboard phase. Could you share your helpful solutions? Thanks!
